/*
 * Copyright 2021 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* eslint-disable max-lines */

export default {
  accesskey: [],
  class: [],
  contenteditable: [],
  contextmenu: [],
  dir: ['ltr', 'rtl'],
  draggable: ['auto', 'false', 'true'],
  dropzone: ['copy', 'move', 'link'],
  hidden: [],
  id: [],
  lang: [
    'ab',
    'aa',
    'af',
    'sq',
    'am',
    'ar',
    'an',
    'hy',
    'as',
    'ay',
    'az',
    'ba',
    'eu',
    'bn',
    'dz',
    'bh',
    'bi',
    'br',
    'bg',
    'my',
    'be',
    'km',
    'ca',
    'zh',
    'co',
    'hr',
    'cs',
    'da',
    'nl',
    'en',
    'eo',
    'et',
    'fo',
    'fa',
    'fi',
    'fr',
    'fy',
    'gl',
    'gd',
    'gv',
    'ka',
    'de',
    'el',
    'kl',
    'gn',
    'gu',
    'ht',
    'ha',
    'he',
    'hi',
    'hu',
    'is',
    'io',
    'id',
    'ia',
    'ie',
    'iu',
    'ik',
    'ga',
    'it',
    'ja',
    'jv',
    'kn',
    'ks',
    'kk',
    'rw',
    'ky',
    'rn',
    'ko',
    'ku',
    'lo',
    'la',
    'lv',
    'li',
    'ln',
    'lt',
    'mk',
    'mg',
    'ms',
    'ml',
    'mt',
    'mi',
    'mr',
    'mo',
    'mn',
    'na',
    'ne',
    'no',
    'oc',
    'or',
    'om',
    'ps',
    'pl',
    'pt',
    'pa',
    'qu',
    'rm',
    'ro',
    'ru',
    'sz',
    'sm',
    'sg',
    'sa',
    'sr',
    'sh',
    'st',
    'tn',
    'sn',
    'ii',
    'sd',
    'si',
    'ss',
    'sk',
    'sl',
    'so',
    'es',
    'su',
    'sw',
    'sv',
    'tl',
    'tg',
    'ta',
    'tt',
    'te',
    'th',
    'bo',
    'ti',
    'to',
    'ts',
    'tr',
    'tk',
    'tw',
    'ug',
    'uk',
    'ur',
    'uz',
    'vi',
    'vo',
    'wa',
    'cy',
    'wo',
    'xh',
    'yi',
    'yo',
    'zu',
  ],
  spellcheck: [],
  style: [],
  tabindex: [],
  title: [],
  onabort: [],
  onblur: [],
  oncanplay: [],
  oncanplaythrough: [],
  onchange: [],
  onclick: [],
  oncontextmenu: [],
  oncuechange: [],
  ondblclick: [],
  ondrag: [],
  ondragend: [],
  ondragenter: [],
  ondragleave: [],
  ondragover: [],
  ondragstart: [],
  ondrop: [],
  ondurationchange: [],
  onemptied: [],
  onended: [],
  onerror: [],
  onfocus: [],
  oninput: [],
  oninvalid: [],
  onkeydown: [],
  onkeypress: [],
  onkeyup: [],
  onload: [],
  onloadeddata: [],
  onloadedmetadata: [],
  onloadstart: [],
  onmousedown: [],
  onmousemove: [],
  onmouseout: [],
  onmouseover: [],
  onmouseup: [],
  onmousewheel: [],
  onpause: [],
  onplay: [],
  onplaying: [],
  onprogress: [],
  onratechange: [],
  onreadystatechange: [],
  onreset: [],
  onscroll: [],
  onseeked: [],
  onseeking: [],
  onselect: [],
  onshow: [],
  onstalled: [],
  onsubmit: [],
  onsuspend: [],
  ontimeupdate: [],
  onvolumechange: [],
  onwaiting: [],
  accept: [
    'text/html',
    'text/plain',
    'application/msword',
    'application/msexcel',
    'application/postscript',
    'application/x-zip-compressed',
    'application/pdf',
    'application/rtf',
    'video/x-msvideo',
    'video/quicktime',
    'video/x-mpeg2',
    'audio/x-pn/realaudio',
    'audio/x-mpeg',
    'audio/x-waw',
    'audio/x-aiff',
    'audio/basic',
    'image/tiff',
    'image/jpeg',
    'image/gif',
    'image/x-png',
    'image/x-photo-cd',
    'image/x-MS-bmp',
    'image/x-rgb',
    'image/x-portable-pixmap',
    'image/x-portable-greymap',
    'image/x-portablebitmap',
  ],
  'accept-charset': [],
  action: [],
  align: [],
  alt: [],
  archive: [],
  async: [],
  autocomplete: [
    'additional-name',
    'address-level1',
    'address-level2',
    'address-level3',
    'address-level4',
    'address-line1',
    'address-line2',
    'address-line3',
    'bday',
    'bday-year',
    'bday-day',
    'bday-month',
    'billing',
    'cc-additional-name',
    'cc-csc',
    'cc-exp',
    'cc-exp-month',
    'cc-exp-year',
    'cc-family-name',
    'cc-given-name',
    'cc-name',
    'cc-number',
    'cc-type',
    'country',
    'country-name',
    'current-password',
    'email',
    'family-name',
    'fax',
    'given-name',
    'home',
    'honorific-prefix',
    'honorific-suffix',
    'impp',
    'language',
    'mobile',
    'name',
    'new-password',
    'nickname',
    'off',
    'on',
    'organization',
    'organization-title',
    'pager',
    'photo',
    'postal-code',
    'sex',
    'shipping',
    'street-address',
    'tel-area-code',
    'tel',
    'tel-country-code',
    'tel-extension',
    'tel-local',
    'tel-local-prefix',
    'tel-local-suffix',
    'tel-national',
    'transaction-amount',
    'transaction-currency',
    'url',
    'username',
    'work',
  ],
  autofocus: [],
  autoplay: [],
  behavior: ['scroll', 'slide', 'alternate'],
  bgcolor: [],
  border: [],
  challenge: [],
  charset: [
    'iso-8859-1',
    'utf-8',
    'shift_jis',
    'euc-jp',
    'big5',
    'gb2312',
    'euc-kr',
    'din_66003-kr',
    'ns_4551-1-kr',
    'sen_850200_b',
    'csISO2022jp',
    'hz-gb-2312',
    'ibm852',
    'ibm866',
    'irv',
    'iso-2022-kr',
    'iso-8859-2',
    'iso-8859-3',
    'iso-8859-4',
    'iso-8859-5',
    'iso-8859-6',
    'iso-8859-7',
    'iso-8859-8',
    'iso-8859-9',
    'koi8-r',
    'ks_c_5601',
    'windows-1250',
    'windows-1251',
    'windows-1252',
    'windows-1253',
    'windows-1254',
    'windows-1255',
    'windows-1256',
    'windows-1257',
    'windows-1258',
    'windows-874',
    'x-euc',
    'asmo-708',
    'dos-720',
    'dos-862',
    'dos-874',
    'cp866',
    'cp1256',
  ],
  checked: [],
  cite: [],
  codebase: [],
  codetype: [],
  cols: [],
  colspan: [],
  content: [],
  controls: [],
  coords: [],
  data: [],
  datetime: [],
  declare: [],
  default: [],
  defer: [],
  direction: ['left', 'right', 'up', 'down'],
  dirname: [],
  disabled: [],
  enctype: ['application/x-www-form-urlencoded', 'multipart/form-data', 'text/plain'],
  for: [],
  form: [],
  formaction: [],
  formenctype: ['application/x-www-form-urlencoded', 'multipart/form-data', 'text/plain'],
  formmethod: ['get', 'post'],
  formnovalidate: [],
  formtarget: ['_blank', '_parent', '_self', '_top'],
  headers: [],
  height: [],
  high: [],
  href: [],
  hreflang: [],
  hspace: [],
  'http-equiv': ['content-type', 'default-style', 'refresh'],
  icon: [],
  ismap: [],
  keytype: ['dsa', 'ec', 'rsa'],
  kind: ['captions', 'chapters', 'descriptions', 'metadata', 'subtitles'],
  label: [],
  list: [],
  longdesc: [],
  loop: [],
  low: [],
  manifest: [],
  max: [],
  maxlength: [],
  media: [
    'screen',
    'tty',
    'tv',
    'projection',
    'handheld',
    'print',
    'aural',
    'braille',
    'embossed',
    'speech',
    'all',
    'width',
    'min-width',
    'max-width',
    'height',
    'min-height',
    'max-height',
    'device-width',
    'min-device-width',
    'max-device-width',
    'device-height',
    'min-device-height',
    'max-device-height',
    'orientation',
    'aspect-ratio',
    'min-aspect-ratio',
    'max-aspect-ratio',
    'device-aspect-ratio',
    'min-device-aspect-ratio',
    'max-device-aspect-ratio',
    'color',
    'min-color',
    'max-color',
    'color-index',
    'min-color-index',
    'max-color-index',
    'monochrome',
    'min-monochrome',
    'max-monochrome',
    'resolution',
    'min-resolution',
    'max-resolution',
    'scan',
    'grid',
  ],
  allowMultipleValues: 'true',
  mediagroup: [],
  method: ['get', 'post'],
  min: [],
  multiple: [],
  muted: [],
  name: [],
  'meta/name': ['application-name', 'author', 'description', 'generator', 'keywords'],
  novalidate: [],
  open: [],
  optimum: [],
  pattern: [],
  placeholder: [],
  poster: [],
  preload: ['auto', 'metadata', 'none'],
  pubdate: [],
  radiogroup: [],
  rel: [
    'alternate',
    'author',
    'bookmark',
    'help',
    'license',
    'next',
    'nofollow',
    'noreferrer',
    'prefetch',
    'prev',
    'search',
    'sidebar',
    'tag',
    'external',
  ],
  'link/rel': [
    'alternate',
    'author',
    'help',
    'icon',
    'license',
    'next',
    'pingback',
    'prefetch',
    'prev',
    'search',
    'sidebar',
    'stylesheet',
    'tag',
  ],
  readonly: [],
  required: [],
  reversed: [],
  rows: [],
  rowspan: [],
  sandbox: ['allow-forms', 'allow-same-origin', 'allow-scripts', 'allow-top-navigation'],
  seamless: [],
  selected: [],
  scope: ['col', 'colgroup', 'row', 'rowgroup'],
  scoped: [],
  scrollamount: [],
  scrolldelay: [],
  shape: ['circle', 'default', 'poly', 'rect'],
  size: [],
  sizes: ['any'],
  span: [],
  src: [],
  srcdoc: [],
  srclang: [],
  standby: [],
  start: [],
  step: [],
  target: ['_blank', '_parent', '_self', '_top'],
  truespeed: [],
  'button/type': ['button', 'reset', 'submit'],
  'command/type': ['command', 'checkbox', 'radio'],
  'link/type': ['text/css'],
  'menu/type': ['context', 'list', 'toolbar'],
  'ol/type': ['1', 'a', 'A', 'i', 'I'],
  'script/type': [
    'text/javascript',
    'text/ecmascript',
    'text/jscript',
    'text/livescript',
    'text/tcl',
    'text/x-javascript',
    'text/x-ecmascript',
    'application/x-javascript',
    'application/x-ecmascript',
    'application/javascript',
    'application/ecmascript',
    'text/babel',
    'text/jsx',
  ],
  'style/type': ['text/css'],
  'input/type': [
    'button',
    'checkbox',
    'color',
    'date',
    'datetime',
    'datetime-local',
    'email',
    'file',
    'hidden',
    'image',
    'month',
    'number',
    'password',
    'radio',
    'range',
    'reset',
    'search',
    'submit',
    'tel',
    'text',
    'time',
    'url',
    'week',
  ],
  usemap: [],
  value: [],
  vspace: [],
  width: [],
  wrap: ['hard', 'soft'],
  'xml:lang': [],
  xmlns: [],
};
