/*
 * Copyright 2021 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export default {
  a: ['href', 'hreflang', 'media', 'rel', 'target', 'type'],
  abbr: [],
  address: [],
  area: ['alt', 'coords', 'href', 'hreflang', 'media', 'rel', 'shape', 'target', 'type'],
  article: [],
  aside: [],
  audio: ['autoplay', 'controls', 'loop', 'mediagroup', 'muted', 'preload', 'src'],
  b: [],
  base: ['href', 'target'],
  bdi: [],
  bdo: [],
  big: [],
  blockquote: ['cite'],
  body: [
    'onafterprint',
    'onbeforeprint',
    'onbeforeunload',
    'onhashchange',
    'onmessage',
    'onoffline',
    'ononline',
    'onpagehide',
    'onpageshow',
    'onpopstate',
    'onredo',
    'onresize',
    'onstorage',
    'onundo',
    'onunload',
  ],
  br: [],
  button: [
    'autofocus',
    'disabled',
    'form',
    'formaction',
    'formenctype',
    'formmethod',
    'formnovalidate',
    'formtarget',
    'name',
    'type',
    'value',
  ],
  canvas: ['height', 'width'],
  caption: [],
  cite: [],
  code: [],
  col: ['span'],
  colgroup: ['span'],
  command: ['checked', 'disabled', 'icon', 'label', 'radiogroup', 'type'],
  datalist: [],
  dd: [],
  del: ['cite', 'datetime'],
  details: ['open'],
  dfn: [],
  dialog: ['open'],
  div: [],
  dl: [],
  dt: [],
  em: [],
  embed: ['height', 'src', 'type', 'width'],
  fieldset: ['disabled', 'form', 'name'],
  figcaption: [],
  figure: [],
  footer: [],
  form: [
    'accept-charset',
    'action',
    'autocomplete',
    'enctype',
    'method',
    'name',
    'novalidate',
    'target',
  ],
  h1: [],
  h2: [],
  h3: [],
  h4: [],
  h5: [],
  h6: [],
  head: [],
  header: [],
  hgroup: [],
  hr: [],
  html: ['manifest', 'xml:lang', 'xmlns'],
  i: [],
  iframe: ['height', 'name', 'sandbox', 'seamless', 'src', 'srcdoc', 'width'],
  ilayer: [],
  img: ['alt', 'height', 'ismap', 'longdesc', 'src', 'usemap', 'width'],
  input: [
    'accept',
    'alt',
    'autocomplete',
    'autofocus',
    'checked',
    'dirname',
    'disabled',
    'form',
    'formaction',
    'formenctype',
    'formmethod',
    'formnovalidate',
    'formtarget',
    'height',
    'list',
    'max',
    'maxlength',
    'min',
    'multiple',
    'name',
    'pattern',
    'placeholder',
    'readonly',
    'required',
    'size',
    'src',
    'step',
    'type',
    'value',
    'width',
  ],
  ins: ['cite', 'datetime'],
  kbd: [],
  keygen: ['autofocus', 'challenge', 'disabled', 'form', 'keytype', 'name'],
  label: ['for', 'form'],
  legend: [],
  li: ['value'],
  link: ['disabled', 'href', 'hreflang', 'media', 'rel', 'sizes', 'type'],
  main: [],
  map: ['name'],
  mark: [],
  marquee: [
    'align',
    'behavior',
    'bgcolor',
    'direction',
    'height',
    'hspace',
    'loop',
    'scrollamount',
    'scrolldelay',
    'truespeed',
    'vspace',
    'width',
  ],
  menu: ['label', 'type'],
  meta: ['charset', 'content', 'http-equiv', 'name'],
  meter: ['form', 'high', 'low', 'max', 'min', 'optimum', 'value'],
  nav: [],
  noscript: [],
  object: [
    'archive',
    'codebase',
    'codetype',
    'data',
    'declare',
    'form',
    'height',
    'name',
    'standby',
    'type',
    'usemap',
    'width',
  ],
  ol: ['reversed', 'start', 'type'],
  optgroup: ['disabled', 'label'],
  option: ['disabled', 'label', 'selected', 'value'],
  output: ['for', 'form', 'name'],
  p: [],
  param: ['name', 'value'],
  pre: [],
  progress: ['form', 'max', 'value'],
  q: ['cite'],
  rp: [],
  rt: [],
  ruby: [],
  samp: [],
  script: ['async', 'charset', 'defer', 'src', 'type'],
  section: [],
  select: ['autofocus', 'disabled', 'form', 'multiple', 'name', 'required', 'size'],
  small: [],
  source: ['media', 'src', 'type'],
  span: [],
  strong: [],
  style: ['disabled', 'media', 'scoped', 'type'],
  sub: [],
  summary: [],
  sup: [],
  table: ['border'],
  tbody: [],
  td: ['colspan', 'headers', 'rowspan'],
  template: ['content'],
  textarea: [
    'autofocus',
    'cols',
    'dirname',
    'disabled',
    'form',
    'label',
    'maxlength',
    'name',
    'placeholder',
    'readonly',
    'required',
    'rows',
    'wrap',
  ],
  tfoot: [],
  th: ['colspan', 'headers', 'rowspan', 'scope'],
  thead: [],
  time: ['datetime', 'pubdate'],
  title: [],
  tr: [],
  track: ['default', 'kind', 'label', 'src', 'srclang'],
  tt: [],
  ul: [],
  var: [],
  video: [
    'autoplay',
    'controls',
    'height',
    'loop',
    'mediagroup',
    'muted',
    'poster',
    'preload',
    'src',
    'width',
  ],
  wbr: [],
};
