/*
 * Copyright 2021 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { IStringMap } from 'cd-interfaces';

export default {
  role: [
    '',
    'alert',
    'alertdialog',
    'application',
    'article',
    'banner',
    'button',
    'cell',
    'checkbox',
    'columnheader',
    'combobox',
    'complementary',
    'contentinfo',
    'definition',
    'dialog',
    'directory',
    'document',
    'feed',
    'figure',
    'form',
    'grid',
    'gridcell',
    'group',
    'heading',
    'img',
    'link',
    'list',
    'listbox',
    'listitem',
    'log',
    'main',
    'marquee',
    'math',
    'menu',
    'menubar',
    'menuitem',
    'menuitemcheckbox',
    'menuitemradio',
    'navigation',
    'none',
    'note',
    'option',
    'presentation',
    'progressbar',
    'radio',
    'radiogroup',
    'region',
    'row',
    'rowgroup',
    'rowheader',
    'scrollbar',
    'search',
    'searchbox',
    'separator',
    'slider',
    'spinbutton',
    'status',
    'switch',
    'tab',
    'table',
    'tablist',
    'tabpanel',
    'term',
    'textbox',
    'timer',
    'toolbar',
    'tooltip',
    'tree',
    'treegrid',
    'treeitem',
  ],
  'aria-autocomplete': ['none', 'inline', 'list', 'both'],
  'aria-current': ['false', 'true', 'page', 'step', 'location', 'date', 'time'],
  'aria-activedescendant': [],
  'aria-atomic': ['false', 'true'],
  'aria-busy': ['false', 'true', 'error'],
  'aria-checked': ['false', 'true', 'mixed'],
  'aria-colcount': [],
  'aria-colindex': [],
  'aria-colspan': [],
  'aria-controls': [],
  'aria-describedby': [],
  'aria-details': [],
  'aria-disabled': ['false', 'true'],
  'aria-expanded': ['false', 'true'],
  'aria-errormessage': [],
  'aria-flowto': [],
  'aria-haspopup': ['false', 'true', 'menu', 'listbox', 'tree', 'grid', 'dialog'],
  'aria-hidden': ['false', 'true'],
  'aria-invalid': ['false', 'true', 'grammar', 'spelling'],
  'aria-keyshortcuts': [],
  'aria-label': [],
  'aria-labelledby': [],
  'aria-level': [],
  'aria-live': ['off', 'polite', 'assertive'],
  'aria-modal': ['false', 'true'],
  'aria-multiline': ['false', 'true'],
  'aria-multiselectable': ['false', 'true'],
  'aria-orientation': ['horizontal', 'vertical'],
  'aria-owns': [],
  'aria-placeholder': [],
  'aria-posinset': [],
  'aria-pressed': ['false', 'true', 'mixed'],
  'aria-readonly': ['false', 'true'],
  'aria-relevant': ['additions', 'removals', 'text', 'all', 'additions text'],
  'aria-required': ['false', 'true'],
  'aria-roledescription': [],
  'aria-rowcount': [],
  'aria-rowindex': [],
  'aria-rowspan': [],
  'aria-selected': ['false', 'true'],
  'aria-setsize': [],
  'aria-sort': ['none', 'ascending', 'descending', 'other'],
  'aria-valuemax': [],
  'aria-valuemin': [],
  'aria-valuenow': [],
  'aria-valuetext': [],
} as IStringMap<string[]>;
